config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }
  
  root "home#index"

  resources :events, only: [:index, :show]

  resources :bookings, only: %i[create] do
    get :booking_details, on: :member 
    get :all_bookings, on: :collection
  end

  namespace :booking do
    resources :events do
      patch :soft_deleted_events, on: :member
    end
  end 
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event

  after_create :update_available_tickets

  def update_available_tickets
    return if event.available_ticket.nil? || no_of_tickets.nil?
    event.update(available_ticket: event.available_ticket - no_of_tickets)
  end

end

app/models/event.rb
class Event < ApplicationRecord
  before_create :set_is_deleted
  paginates_per 10

  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings

  has_many_attached :images


  TICKET_PRICE = [499,799,999]

  validates :title, :description, :location, :date, :time, presence: true
  validates :ticket_price, :available_ticket, presence: true, numericality: true 
  
  scope :sold_out, -> { includes(:users).where(available_ticket: 0) }  
  scope :current_events, -> { includes(:users).where("date > ?", Date.today ).where(is_deleted: false) }  
  scope :ended_events, -> { includes(:users).where("date < ?", Date.today ) } 

  scope :soft_deleted, -> { where(is_deleted: true) } 

  def create_booking(user_id, event_id)
    Booking.create!(user_id: user_id, event_id: event_id)
  end

  def is_upcoming_event?
    date > Date.today 
  end

  def set_is_deleted
    self.is_deleted = false if is_deleted.nil?
  end

  def set_true_is_deleted
    is_deleted  == false
  end

  def set_false_is_deleted
    is_deleted  == true
  end

end

app/controllers/booking/events_controller.rb
class Booking::EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :soft_deleted_events ]
  before_action :authorized_organizer, only: [:new, :create, :update, :destroy]

  def index
    @current_events = current_user.events.current_events.includes(:users).order(created_at: :desc).page(params[:page]).per(9)

    @sold_events = current_user.events.sold_out.order(:created_at).page(params[:page]).per(9)

    @ended_events = current_user.events.ended_events.order(:created_at).page(params[:page]).per(9)

    @soft_deleted_events = current_user.events.soft_deleted
  end

  def new
    @event = current_user.events.new
  end

  def create
    @event = current_user.events.new(set_params)
    if @event.save
      @event.create_booking(current_user.id, @event.id)
      redirect_to booking_events_path, notice: "Event Create Successfully"
    else 
      render :new, status: :unprocessable_entity
    end
  end

  def show 
  end

  def edit
  end

  def update
    if current_user.organizer?
      if @event.update(set_params)
        redirect_to booking_events_path, notice: "Event Update Succesfully"
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    if @event.destroy
      redirect_to events_path,  notice: "Event deleted Successfully"
    end
  end

  def soft_deleted_events
    if @event.is_deleted == false
      @event.update(is_deleted: true)
    else
      @event.update(is_deleted: false)
    end
    flash[:notice] = "Event deleted successfully."
    redirect_to  action: :index    
  end

  private 

  def set_params
    params.require(:event).permit(:title, :description, :location, :date, :time, :ticket_price, :available_ticket, images: [])
  end

  def set_event
    @event = Event.find(params[:id])
    @user = current_user
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @stripe_service = StripeService.new
    @event = Event.find(params[:event_id])
    @user = User.find_by(email: params[:email])
    unless @user.present?
      @user = User.create(customer_params)
    end

    @stripe_user = @stripe_service.find_or_create_user(@user)

    @card = @stripe_service.create_stripe_customer_card(card_params, @stripe_user)

    @amount = (params[:no_of_tickets].to_i * @event.ticket_price).to_i

    @charge = @stripe_service.create_stripe_charge(@amount, @stripe_user.id, @card.id, @event)

    @booking = @event.bookings.create(
      user_id: @user.id, 
      stripe_transaction_id: @charge.id, 
      no_of_tickets: params[:no_of_tickets].to_i,
      price_paid: @amount
    )
    BookingsMailer.booking_confirmation(@booking).deliver_now
    redirect_to event_path(@event), notice: "Your Tickets has been booked"

  rescue Stripe::StripeError => error
    redirect_to event_path(@event), alert: "#{error.message}"
  end

  def all_bookings
    @bookings = current_user.bookings.includes(:event)
  end

  def booking_details
    @booking = Booking.find(params[:id])
  end

  private

  def customer_params
    params.permit(:full_name, :email, :contact_number).merge(role: "Attendee")
  end

  def card_params
    params.permit(:card_number, :cvv, :exp_month, :exp_year)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @current_events = Event.current_events.order(created_at: :desc).page(params[:page]).per(9)
    @sold_events = Event.sold_out.order(:created_at).page(params[:page]).per(9)

    @ended_events = Event.ended_events.order(:created_at).page(params[:page]).per(9)
  end

  def show
    @event = Event.find(params[:id])
  end
  
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def qr_code_svg_for(booking)
    qrcode = RQRCode::QRCode.new(booking_root_url(booking))
    qrcode.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: 4,
      standalone: true,
      use_path: true
    )
  end

  private

  def booking_root_url(booking_id)
    if Rails.env.development?
      "http://localhost:3000/bookings/#{booking_id}/booking_details"
    else
      #later TODO
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/booking/events/_form.html.erb
<%= form_with model: [:booking, event] do |form| %> 
  <div class="row">
    <div class="col-lg-4 mb-3">
      <div class="form-group">
        <%= form.label :images, class: "mb-2" %>
        <%= form.file_field :images, multiple: true, class: "form-control form-control-lg rounded-0" %>
        <% @event.errors.full_messages_for(:title).each do |message| %>
        <p class="text-danger"><%= message%></p>
        <% end %>
      </div>        
    </div>
    <div class="col-lg-4 mb-3">
      <div class="form-group">
        <%= form.label :title, class: "mb-2" %>
        <%= form.text_field :title, class: "form-control form-control-lg rounded-0" %>
        <% @event.errors.full_messages_for(:title).each do |message| %>
        <p class="text-danger"><%= message%></p>
        <% end %>
      </div>        
    </div>
    <div class="col-lg-4 mb-3">
      <div class="form-group">
        <%= form.label :description, class: "mb-2" %>
        <%= form.text_area :description, class: "form-control form-control-lg rounded-0" %>
        <% @event.errors.full_messages_for(:description).each do |message| %>
        <p class="text-danger"><%= message%></p>
        <% end %>
      </div>        
    </div>
    <div class="col-lg-4 mb-3">
      <div class="form-group">
        <%= form.label :location, class: "mb-2" %>
        <%= form.text_field :location, class: "form-control form-control-lg rounded-0" %>
        <% @event.errors.full_messages_for(:location).each do |message| %>
        <p class="text-danger"><%= message%></p>
        <% end %>
      </div>        
    </div>
    <div class="col-lg-4 mb-3">
      <div class="form-group">
        <%= form.label :date, class: "mb-2" %>
        <%= form.date_field :date, class: "form-control form-control-lg rounded-0" %>
        <% @event.errors.full_messages_for(:date).each do |message| %>
        <p class="text-danger"><%= message%></p>
        <% end %>
      </div>        
    </div>
    <div class="col-lg-4 mb-3">
      <div class="form-group">
        <%= form.label :time, class: "mb-2" %>
        <%= form.time_field :time, class: "form-control form-control-lg rounded-0 b-form-timepicker" %>
        <% @event.errors.full_messages_for(:time).each do |message| %>
        <p class="text-danger"><%= message%></p>
        <% end %>
      </div>        
    </div>
    <div class="col-lg-4 mb-3">
      <div class="form-group">
        <%= form.label :ticket_price, class: "mb-2" %>
        <%= form.text_field :ticket_price, class: "form-control form-control-lg rounded-0" %>
        <% @event.errors.full_messages_for(:ticket_price).each do |message| %>
        <p class="text-danger"><%= message%></p>
        <% end %>
      </div>        
    </div>
    <div class="col-lg-4 mb-3">
      <div class="form-group">
        <%= form.label :available_ticket, class: "mb-2" %>
        <%= form.text_field :available_ticket, class: "form-control form-control-lg rounded-0" %>
        <% @event.errors.full_messages_for(:available_ticket).each do |message| %>
        <p class="text-danger"><%= message%></p>
        <% end %>
      </div>        
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 mt-4">
      <%= form.submit class: "btn btn-primary rounded-0" %>
      <%= link_to "Back to Event", booking_events_path, class: "btn btn-outline-primary rounded-0" %>
    </div>
  </div>
<% end %>

app/views/booking/events/edit.html.erb
<div class="col-lg-12">
  <div class="card mt-5 mb-5 rounded-0">
    <div class="card-body">
      <h2 class="text-center">Edit Event</h2>
    </div>
  </div>

  <%= render 'form', event: @event %>
</div>

app/views/booking/events/index.html.erb
<%= render 'shared/event_card' %>

app/views/booking/events/new.html.erb
<div class="col-lg-12">
  <div class="card mt-5 mb-5 rounded-0">
    <div class="card-body">
      <h2 class="text-center">Create New Event</h2>
    </div>
  </div>

  <%= render 'form', event: @event %>
</div>

app/views/booking/events/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card mt-3 mb-3 rounded-0">
      <div class="card-body">
        <h2 class="text-center">Event Information</h2>
        <div class="row mt-4">
          <% @event.images.each do |image| %>
            <% if @event.images.attached? %>
              <%= image_tag image, class: 'img-fluid w-25 mx-auto' %>
            <% end %>
          <% end %>
            <p class="lead fw-bold text-capitalize text-center"><%= @event.title %></p>
            <p class="lead"><%= @event.description %></p>
            <p class="lead"><%= @event.location %></p>
            <p class="lead"><%= @event.date %></p>
            <p class="lead"><%= @event.time.strftime("%I:%M %p") %></p>
            <p class="lead text-primary"><i class="bi bi-currency-rupee"></i><%= @event.ticket_price %></p>
            <p class="lead"><%= @event.available_ticket %></p>
        </div>

        <%#= link_to 'Buy Tickets', events_path, class: "btn btn-outline-primary rounded-0" %>
        <%= link_to 'Back To Events', request.referrer, class: "btn btn-outline-primary rounded-0" %>
          
        <% if current_user.organizer? %>
          <%= link_to 'Edit Events', edit_booking_event_path(@event), class: "btn btn-primary rounded-0" %>
          <%#= link_to 'Delete Events', booking_event_path(@event), data: { turbo_method: :delete, turbo_confirm: "Are you sure to delete this event" } ,class: "btn btn-danger rounded-0" %>
          <% if @event.set_true_is_deleted %>
            <%= link_to 'Delete Events', soft_deleted_events_booking_event_path(@event), method: :patch ,class: "btn btn-danger rounded-0" %>
          <% else %>
            <%= link_to 'Live Again', soft_deleted_events_booking_event_path(@event), method: :patch ,class: "btn btn-danger rounded-0" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>