config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }
  
  root "home#index"

  resources :events, only: [:index, :show]

  resources :bookings, only: %i[create] do
    get :booking_details, on: :member 
    get :all_bookings, on: :collection
  end

  namespace :booking do
    resources :events do
      patch :soft_deleted_events, on: :member
    end
  end 
end

app/views/shared/_event_card.html.erb
<div class="mt-3 mb-3">
  <div class="row">
    <div class="col-lg-12">
      <div class="card text-center mb-2">
        <div class="card-header">
          <h2 class="fw-bold">Present Events</h3>
        </div>
      </div>
    </div>
    <% if @current_events.present? %>
      <% @current_events.each do |event| %>
        <div class="col-lg-4">
        <div class="card shadow mb-5">
          <div class="card-body text-center">
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrq8mdQOGc0FwzK4t6d7dn6SdSaCJXbyGb0g&s" %>
            <p class="lead fw-bold text-primary "><%= event.title %></p>
            <p class="lead text-truncate"><%= event.description %></p>
            <p class="lead "><small><%= event.date&.strftime("%B %d, %Y") %> <%= event.time&.strftime("%I:%M %p") %></small></p>
            <% if current_user.organizer? %>
              <%= link_to 'View', booking_event_path(event), class: "btn btn-primary" %>
            <% else %>
              <%= link_to 'View', event_path(event), class: "btn btn-primary" %>
            <% end %>
            <% if current_user.organizer? %>
              <%= link_to 'Delete', soft_deleted_events_booking_event_path(event), class: "btn btn-danger", data: { turbo_method: :patch, turbo_confirm: "Are you Sure to delete this event" } %>
            <% end %>
          </div>
        </div>
        </div>
      <% end %>
    <% else %>
      <h1 class="text-center">Sorry! No Event at the moment</h1>
    <% end %>
  </div>
</div>
<%= paginate @current_events if @current_events.present? %>

<hr>

<div class="mt-3 mb-3">
  <div class="row">
    <div class="col-lg-12">
      <div class="card text-center mb-2">
        <div class="card-header">
          <h2 class="fw-bold">Soft Deleted Events</h3>
        </div>
      </div>
    </div>
    <% if @soft_deleted_events.present? %>
      <% @soft_deleted_events.each do |event| %>
        <div class="col-lg-4">
        <div class="card shadow mb-5">
          <div class="card-body text-center">
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrq8mdQOGc0FwzK4t6d7dn6SdSaCJXbyGb0g&s" %>
            <p class="lead fw-bold text-primary "><%= event.title %></p>
            <p class="lead text-truncate"><%= event.description %></p>
            <p class="lead "><small><%= event.date&.strftime("%B %d, %Y") %> <%= event.time&.strftime("%I:%M %p") %></small></p>
            <% if current_user.organizer? %>
              <%= link_to 'View', booking_event_path(event), class: "btn btn-primary" %>
            <% else %>
              <%= link_to 'View', event_path(event), class: "btn btn-primary" %>
            <% end %>
            <% if current_user.organizer? %>
              <%= link_to 'Delete', booking_event_path(event), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are you Sure to delete this event" } %>
            <% end %>
          </div>
        </div>
        </div>
      <% end %>
    <% else %>
      <h1 class="text-center">Sorry! No Event at the moment</h1>
    <% end %>
  </div>
</div>

<hr>

<div class="mt-3 mb-3">
  <div class="row">
    <div class="col-lg-12">
      <div class="card text-center mb-2">
        <div class="card-header">
          <h2 class="fw-bold">Sold Events List</h3>
        </div>
      </div>
    </div>
    <% if @sold_events.present? %>
      <% @sold_events.each do |event| %>
        <div class="col-lg-4">
        <div class="card shadow mb-5">
          <div class="card-body text-center">
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrq8mdQOGc0FwzK4t6d7dn6SdSaCJXbyGb0g&s" %>
            <p class="lead fw-bold text-primary "><%= event.title %></p>
            <p class="lead text-truncate"><%= event.description %></p>
            <p class="lead "><small><%= event.date&.strftime("%B %d, %Y") %> <%= event.time&.strftime("%I:%M %p") %></small></p>
            <% if current_user.organizer? %>
              <%= link_to 'View', booking_event_path(event), class: "btn btn-primary" %>
            <% else %>
              <%= link_to 'View', event_path(event), class: "btn btn-primary" %>
            <% end %>
            <% if current_user.organizer? %>
              <%= link_to 'Delete', booking_event_path(event), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are you Sure to delete this event" } %>
            <% end %>
          </div>
        </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<%= paginate @sold_events if @sold_events.present? %>
<hr>


<div class="mt-3 mb-3">
  <div class="row">
    <div class="col-lg-12">
      <div class="card text-center mb-2">
        <div class="card-header">
          <h2 class="fw-bold">Ended Events List</h3>
        </div>
      </div>
    </div>
    <% if @ended_events.present? %>
      <% @ended_events.each do |event| %>
        <div class="col-lg-4">
        <div class="card shadow mb-5">
          <div class="card-body text-center">
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrq8mdQOGc0FwzK4t6d7dn6SdSaCJXbyGb0g&s" %>
            <p class="lead fw-bold text-primary "><%= event.title %></p>
            <p class="lead text-truncate"><%= event.description %></p>
            <p class="lead "><small><%= event.date&.strftime("%B %d, %Y") %> <%= event.time&.strftime("%I:%M %p") %></small></p>
            <% if current_user.organizer? %>
              <%= link_to 'View', booking_event_path(event), class: "btn btn-primary" %>
            <% else %>
              <%= link_to 'View', event_path(event), class: "btn btn-primary" %>
            <% end %>
            <% if current_user.organizer? %>
              <%= link_to 'Delete', booking_event_path(event), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are you Sure to delete this event" } %>
            <% end %>
          </div>
        </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<%= paginate @ended_events if @ended_events.present? %>

app/views/shared/_flash.html.erb
<div id="flash">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key.to_sym) %> alert-dismissible fade show" role="alert" >
      <% unless value == true %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= value %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to 'Event-Management', root_path, class: 'navbar-brand text-decoration-none text-white' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure to sign out?" }, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <% if current_user.organizer? %>
              <%= link_to 'Events', booking_events_path, class: "nav-link active" %>
            <% else %>
              <%= link_to 'Events', events_path, class: "nav-link active" %>
            <% end %>  
          </li>
          <li class="nav-items">
            <%= link_to 'Bookings', all_bookings_bookings_path, class: "nav-link active" %>
          </li>
          <% if current_user.organizer? %>
            <li class="nav-item">
              <%= link_to 'Create Event', new_booking_event_path, class: "nav-link active" %>
            </li>
          <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link active text-decoration-none" %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "#{current_user.email}", edit_user_registration_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <small class="nav-link active"><%= "#{current_user.role}" %></small>
          </li>
        <% end %>
      </ul>
      </div>
    </div>
  </nav>